services:
  - type: web
    name: compute-rus
    env: node
    plan: free
    buildCommand: npm ci --include=dev && npm run build
    startCommand: node dist/server.js
    autoDeploy: true
    envVars:
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
